# Generated by Django 5.0.7 on 2024-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=20)),
                ('Avaliacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('esta_avaliado', models.BooleanField(default=0)),
            ],
            options={
                'unique_together': {('numero', 'codigo')},
            },
        ),
    ]
