# Generated by Django 5.0.7 on 2024-09-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoMontador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('esta_avaliado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('esta_avaliado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('cliente', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='api.pedido')),
            ],
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.AddField(
            model_name='avaliacaomotorista',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_motorista', to='api.pedido'),
        ),
        migrations.AddField(
            model_name='avaliacaomontador',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_montador', to='api.pedido'),
        ),
    ]
