# Generated by Django 5.0.7 on 2024-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_avaliacaomontador_avaliacaomotorista_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
