# Generated by Django 5.0.7 on 2024-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pedido_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaomontador',
            name='esta_avaliado',
        ),
        migrations.RemoveField(
            model_name='avaliacaomotorista',
            name='esta_avaliado',
        ),
        migrations.AddField(
            model_name='avaliacaomontador',
            name='cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaomotorista',
            name='cliente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
