# Generated by Django 5.0.7 on 2024-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_avaliacaomontador_esta_avaliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaomontador',
            name='montador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaomotorista',
            name='motorista',
            field=models.TextField(blank=True, null=True),
        ),
    ]
