# Generated by Django 5.0.7 on 2024-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_avaliacaomontador_montador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tracking',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
    ]
