# Generated by Django 5.0.7 on 2024-09-17 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
