# Generated by Django 5.0.7 on 2024-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_progresso_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='url',
            field=models.TextField(default=None, null=True),
        ),
    ]
